### PR TITLE
add back v1beta1 CRD for 4.2 clusters

### PR DESCRIPTION
**Pull request by mrogers950**
@jhrozek @JAORMX  - Brought up in https://github.com/mrogers950/file-integrity-operator/pull/11#issuecomment-550015288 , let's keep the ability to install on <= 4.2 for now.

### CODE REVIEW

**Comment by jhrozek** [comment]
btw I was just asking in that other PR :) If we want to target v1 of an API, that's a fair choice as well, it just needs to be clearly documented in the README.

My personal opinion is that supporting the latest released version is in general a good thing as it lowers the bar to test the code, though.

**Comment by JAORMX** [comment]
The other option is to stick with v1beta1; but then the CRD needs to be compliant. The current one (if set with v1beta1) is kind of a hybrid and not really compliant. As told my Stefan, this was more of a workaround at the time.

**Comment by jhrozek** [comment]
In what way it is not compliant?

**Comment by JAORMX** [comment]
@jhrozek #10 is the way a v1beta1 CRD should look like.

**Comment by jhrozek** [comment]
Ah, OK. Ozz also pointed me to https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition which shows the diff between a beta and v1 api. With that I agree that it is much nicer to stick with v1 and drop the legacy baggage early.

The only thing I'd ask for is to add a note to README that this operator requires k8s 1.16 - we probably don't want people who might try the operator now (QE? People reviewing the enhancement proposal?) to get frustrated by not being able to deploy..

Sorry about the noise.

**Comment by mrogers950** [comment]
Closing, we decided to not worry about 4.2 clusters for the time being, and keep v1

**Pull request closed without merging**
